// Contract codegen. Sources of truth (all post-integration, on rc/v0.1):
//   1. ../schemas/*.schema.json           → types via json-schema-to-typescript
//   2. ../docs/rfc-002-engine-design.md   → §3 canonical state tables + §2.2 closed
//      column sets, parsed into enums/edges/legality maps. RFC-002 §3 states that
//      SDK enums "are generated from or validated against this section"; schemas/README
//      pins the record-schema deferral and mandates generation from the ratified table,
//      never hand-copying.
// Output is committed under src/shared/contracts/generated/; --check fails on drift.
// contracts/schema-pins.json records the SHA-256 of every consumed source.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const webRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const repoRoot = dirname(webRoot);
const outDir = join(webRoot, "src", "shared", "contracts", "generated");
const pinsPath = join(webRoot, "contracts", "schema-pins.json");
const check = process.argv.includes("--check");

const SOURCES = {
  intentContract: join(repoRoot, "schemas", "intent-contract.schema.json"),
  capabilityDeclaration: join(repoRoot, "schemas", "capability-declaration.schema.json"),
  effectRecord: join(repoRoot, "schemas", "effect-record.schema.json"),
  dispatchReceipt: join(repoRoot, "schemas", "dispatch-receipt.schema.json"),
  reconciliationFinding: join(repoRoot, "schemas", "reconciliation-finding.schema.json"),
  rfc002: join(repoRoot, "docs", "rfc-002-engine-design.md"),
  exampleOrderCreate: join(
    repoRoot,
    "schemas",
    "examples",
    "intent-contract",
    "valid-order-create.json",
  ),
  exampleRefund: join(
    repoRoot,
    "schemas",
    "examples",
    "intent-contract",
    "valid-refund-single-id.json",
  ),
};

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

// ---------- 1. JSON Schema → TypeScript ----------

async function generateSchemaTypes() {
  const banner =
    "/* eslint-disable */\n" +
    "/* AUTO-GENERATED by scripts/codegen.mjs — DO NOT EDIT.\n" +
    "   Source: schemas/*.schema.json (trust boundary; changes require an ADR). */\n\n";
  const files = {};
  for (const [name, file] of [
    ["intent-contract", SOURCES.intentContract],
    ["capability-declaration", SOURCES.capabilityDeclaration],
    ["effect-record", SOURCES.effectRecord],
    ["dispatch-receipt", SOURCES.dispatchReceipt],
    ["reconciliation-finding", SOURCES.reconciliationFinding],
  ]) {
    const schema = JSON.parse(readFileSync(file, "utf8"));
    const ts = await compile(schema, schema.title ?? name, {
      bannerComment: "",
      additionalProperties: false,
      style: { printWidth: 96 },
    });
    files[`${name}.ts`] = banner + ts;
  }
  return files;
}

// ---------- 2. RFC-002 §3 state tables + §2.2 closed sets ----------

function section(md, heading, nextHeadingRe) {
  const start = md.indexOf(heading);
  if (start === -1) throw new Error(`RFC-002 section not found: ${heading}`);
  const rest = md.slice(start + heading.length);
  const end = rest.search(nextHeadingRe);
  return end === -1 ? rest : rest.slice(0, end);
}

const ESCAPED_PIPE = "\u0000";

function tableRows(text) {
  return text
    .split("\n")
    .filter((l) => l.trim().startsWith("|"))
    .map((l) =>
      l
        .replaceAll("\\|", ESCAPED_PIPE)
        .split("|")
        .slice(1, -1)
        .map((c) => c.replaceAll(ESCAPED_PIPE, "|").trim()),
    )
    .filter((cells) => !cells.every((c) => /^[-\s:]*$/.test(c)));
}

/** Extract a CHECK (col IN ('A','B')) closed set from the §2.2 DDL. */
function sqlClosedSet(md, column) {
  const re = new RegExp(`${column}[^(]*(?:IN|IN\\s*)\\(([^)]*)\\)`, "s");
  const m = re.exec(md);
  if (!m) throw new Error(`closed set not found in DDL for column: ${column}`);
  return [...m[1].matchAll(/'([A-Za-z0-9_]+)'/g)].map((x) => x[1]);
}

function parseStateModel() {
  const md = readFileSync(SOURCES.rfc002, "utf8");

  // §3.1 lifecycle edges
  const s31 = section(md, "### 3.1", /\n### /);
  const edgeRows = tableRows(s31).slice(1); // drop header
  const lifecycleEdges = edgeRows.map(([from, to, cause, actors]) => ({
    from: from.includes("genesis") ? null : from.replace(/[^A-Z_]/g, ""),
    to: to.replace(/[^A-Z_]/g, ""),
    causes: [...cause.matchAll(/`([a-z_]+)`/g)].map((m) => m[1]),
    actors: actors
      .split(",")
      .map((a) => a.trim().replace(/[^a-z_]/g, ""))
      .filter(Boolean),
  }));
  const lifecycleStates = [...new Set(lifecycleEdges.flatMap((e) => [e.from, e.to]))].filter(
    (s) => s !== null,
  );
  const terminalMatch = /([A-Z_,\s]+) are terminal \*\*per execution\*\*/.exec(s31);
  if (!terminalMatch) throw new Error("terminal-state sentence not found in §3.1");
  const terminalStates = terminalMatch[1]
    .split(",")
    .map((s) => s.trim())
    .filter((s) => /^[A-Z_]+$/.test(s));

  // Closed sets straight from the ratified DDL (§2.2)
  const effectClasses = sqlClosedSet(md, "effect_class");
  const classifications = sqlClosedSet(md, "classification");
  const transportOutcomes = sqlClosedSet(md, "transport_outcome");
  const transitionActors = sqlClosedSet(md, "actor\\s+text\\s+NOT NULL CHECK \\(actor");
  const attemptKinds = sqlClosedSet(md, "kind");
  const openedBy = sqlClosedSet(md, "opened_by");
  const probeResults = sqlClosedSet(md, "result");

  // §3.2 A×B attachment legality
  const s32 = section(md, "### 3.2", /\n### /);
  const abRows = tableRows(s32);
  const abHeader = abRows[0].slice(1).map((h) => h.replace(/[^A-Z_]/g, ""));
  const classificationAttachment = {};
  for (const row of abRows.slice(1)) {
    const frontiers = row[0].split("/").map((f) => f.trim().replace(/[^A-Z_]/g, ""));
    for (const frontier of frontiers) {
      classificationAttachment[frontier] = {};
      abHeader.forEach((cls, i) => {
        classificationAttachment[frontier][cls] =
          /LEGAL/.test(row[i + 1]) && !/^ILLEGAL/.test(row[i + 1].replace(/\*/g, "").trim())
            ? "LEGAL"
            : "ILLEGAL";
      });
    }
  }

  // §3.3 B×C resolution legality + status chain
  const s33 = section(md, "### 3.3", /\n## /);
  const chainMatch = /`OPEN → \{([^}]+)\}`;\s*\n?`ESCALATED_HUMAN → \{([^}]+)\}`/.exec(s33);
  if (!chainMatch) throw new Error("resolution status chain not found in §3.3");
  const openActions = chainMatch[1].split("|").map((s) => s.trim());
  const escalatedActions = chainMatch[2].split("|").map((s) => s.trim());
  const resolutionStatuses = ["OPEN", ...openActions, "CLOSED"];
  const bcRows = tableRows(s33);
  const bcHeader = bcRows[0].slice(1).map((h) => h.replace(/[^A-Z_]/g, ""));
  const resolutionLegality = {};
  for (const row of bcRows.slice(1)) {
    const cls = row[0].replace(/[^A-Z_]/g, "");
    resolutionLegality[cls] = {};
    bcHeader.forEach((action, i) => {
      const cell = row[i + 1].replace(/\*/g, "").trim();
      resolutionLegality[cls][action] = cell.startsWith("ILLEGAL")
        ? "ILLEGAL"
        : cell.startsWith("auto")
          ? "AUTO"
          : "LEGAL";
    });
  }

  return {
    lifecycleStates,
    terminalStates,
    lifecycleEdges,
    effectClasses,
    classifications,
    transportOutcomes,
    transitionActors,
    attemptKinds,
    openedBy,
    probeResults,
    classificationAttachment,
    resolutionStatuses,
    openActions,
    escalatedActions,
    resolutionLegality,
  };
}

function renderStateModel(model) {
  const lit = (arr) => arr.map((v) => JSON.stringify(v)).join(" | ");
  const arr = (a) => JSON.stringify(a, null, 2);
  return `/* eslint-disable */
/* AUTO-GENERATED by scripts/codegen.mjs — DO NOT EDIT.
   Source: docs/rfc-002-engine-design.md §3 (THE ratified state model; single source
   of truth) and the §2.2 ledger DDL closed sets. Regenerate with \`pnpm codegen\`. */

export type Lifecycle = ${lit(model.lifecycleStates)};
export type Classification = ${lit(model.classifications)};
export type ResolutionStatus = ${lit(model.resolutionStatuses)};
export type EffectClass = ${lit(model.effectClasses)};
export type TransportOutcome = ${lit(model.transportOutcomes)};
export type TransitionActor = ${lit(model.transitionActors)};
export type AttemptKind = ${lit(model.attemptKinds)};
export type ExecutionOpenedBy = ${lit(model.openedBy)};
export type ProbeResult = ${lit(model.probeResults)};

export const LIFECYCLE_STATES = ${arr(model.lifecycleStates)} as const satisfies readonly Lifecycle[];
export const TERMINAL_LIFECYCLE_STATES = ${arr(model.terminalStates)} as const satisfies readonly Lifecycle[];
export const CLASSIFICATIONS = ${arr(model.classifications)} as const satisfies readonly Classification[];
export const RESOLUTION_STATUSES = ${arr(model.resolutionStatuses)} as const satisfies readonly ResolutionStatus[];
export const EFFECT_CLASSES = ${arr(model.effectClasses)} as const satisfies readonly EffectClass[];
export const TRANSPORT_OUTCOMES = ${arr(model.transportOutcomes)} as const satisfies readonly TransportOutcome[];

export interface LifecycleEdge {
  /** null = genesis */
  from: Lifecycle | null;
  to: Lifecycle;
  causes: readonly string[];
  actors: readonly TransitionActor[];
}

/** §3.1 — every (from, to) pair not listed is illegal. */
export const LIFECYCLE_EDGES = ${arr(model.lifecycleEdges)} as const satisfies readonly LifecycleEdge[];

/** §3.2 — classification attachment legality per lifecycle frontier. */
export const CLASSIFICATION_ATTACHMENT = ${arr(model.classificationAttachment)} as const satisfies Record<
  Lifecycle,
  Record<Classification, "LEGAL" | "ILLEGAL">
>;

/** §3.3 — resolution status chain. */
export const RESOLUTION_ACTIONS_FROM_OPEN = ${arr(model.openActions)} as const;
export const RESOLUTION_ACTIONS_FROM_ESCALATED = ${arr(model.escalatedActions)} as const;

/** §3.3 — action legality per classification. AUTO = system actor, same settle txn. */
export const RESOLUTION_LEGALITY = ${arr(model.resolutionLegality)} as const satisfies Record<
  Classification,
  Record<string, "LEGAL" | "ILLEGAL" | "AUTO">
>;
`;
}

// ---------- 3. Pins + write/check ----------

function renderIdentityExamples() {
  const order = JSON.parse(readFileSync(SOURCES.exampleOrderCreate, "utf8"));
  const refund = JSON.parse(readFileSync(SOURCES.exampleRefund, "utf8"));
  return `/* eslint-disable */
/* AUTO-GENERATED by scripts/codegen.mjs — DO NOT EDIT.
   Source: schemas/examples/intent-contract/valid-*.json (canonical schema
   example suite — the executable form of the registrar's acceptance rules). */
import type { IntentContract } from "./intent-contract";

export const EXAMPLE_ORDER_CREATE = ${JSON.stringify(order, null, 2)} as const satisfies IntentContract;

export const EXAMPLE_REFUND_SINGLE_ID = ${JSON.stringify(refund, null, 2)} as const satisfies IntentContract;
`;
}

async function main() {
  const files = await generateSchemaTypes();
  files["state-model.ts"] = renderStateModel(parseStateModel());
  files["identity-examples.ts"] = renderIdentityExamples();

  const pins = {
    $comment:
      "SHA-256 pins of every contract source consumed by web codegen. A mismatch means a schema or the ratified state table changed: regenerate, revalidate fixtures, review.",
    generated_by: "scripts/codegen.mjs",
    sources: Object.fromEntries(
      Object.entries(SOURCES).map(([k, p]) => [
        p.replace(`${repoRoot}/`, ""),
        { sha256: sha256(readFileSync(p)), role: k },
      ]),
    ),
  };
  files["../../../../contracts/schema-pins.json"] = `${JSON.stringify(pins, null, 2)}\n`;

  mkdirSync(outDir, { recursive: true });
  mkdirSync(dirname(pinsPath), { recursive: true });

  let drift = false;
  for (const [rel, content] of Object.entries(files)) {
    const target = rel.startsWith("../") ? pinsPath : join(outDir, rel);
    if (check) {
      if (!existsSync(target) || readFileSync(target, "utf8") !== content) {
        console.error(`DRIFT: ${target}`);
        drift = true;
      }
    } else {
      writeFileSync(target, content);
      console.log(`wrote ${target.replace(`${webRoot}/`, "")}`);
    }
  }
  if (check && drift) process.exit(1);
  if (check) console.log("codegen output in sync with contract sources");
}

await main();
