// Content collections: rendered repository docs (generated by
// scripts/sync-docs.mjs — never hand-edited), the authored docs guides, and
// research posts. Frontmatter `claims` arrays are validated against the
// claims registry at build time: an unknown claim id fails the build.
import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";
import { claims } from "./data/claims";

const claimId = z.enum(Object.keys(claims) as [string, ...string[]]);
const badge = z.enum(["recorded", "conceptual", "preregistered"]);

const repoDocs = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/repo-docs" }),
  schema: z.object({
    title: z.string(),
    description: z.string().optional(),
    sourcePath: z.string(),
    sourceSha256: z.string().regex(/^[0-9a-f]{64}$/),
    syncedAt: z.string(),
    section: z.string(),
    renderTitle: z.boolean(),
    badge: badge.optional(),
    adr: z
      .object({
        id: z.string(),
        status: z.string().optional(),
        date: z.string().optional(),
        supersedes: z.string().optional(),
      })
      .optional(),
  }),
});

const guides = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/guides" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    order: z.number(),
    badge: badge.optional(),
    claims: z.array(claimId).default([]),
    generated: z
      .object({
        command: z.string(),
        capturedSha256: z.string().regex(/^[0-9a-f]{64}$/),
      })
      .optional(),
  }),
});

const research = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/research" }),
  schema: z.object({
    title: z.string(),
    date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    summary: z.string(),
    badges: z.array(badge).default([]),
    claims: z.array(claimId).default([]),
    sources: z.array(z.object({ label: z.string(), url: z.string() })).default([]),
  }),
});

export const collections = { "repo-docs": repoDocs, guides, research };
