/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxonomyRouteImport } from './routes/taxonomy'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EffectsIndexRouteImport } from './routes/effects.index'
import { Route as LearnTiersRouteImport } from './routes/learn.tiers'
import { Route as LearnStateRouteImport } from './routes/learn.state'
import { Route as LearnStartRouteImport } from './routes/learn.start'
import { Route as LearnIdentityRouteImport } from './routes/learn.identity'

const TaxonomyRoute = TaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectsIndexRoute = EffectsIndexRouteImport.update({
  id: '/effects/',
  path: '/effects/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTiersRoute = LearnTiersRouteImport.update({
  id: '/learn/tiers',
  path: '/learn/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnStateRoute = LearnStateRouteImport.update({
  id: '/learn/state',
  path: '/learn/state',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnStartRoute = LearnStartRouteImport.update({
  id: '/learn/start',
  path: '/learn/start',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIdentityRoute = LearnIdentityRouteImport.update({
  id: '/learn/identity',
  path: '/learn/identity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/attention': typeof AttentionRoute
  '/bench': typeof BenchRoute
  '/demo': typeof DemoRoute
  '/findings': typeof FindingsRoute
  '/health': typeof HealthRoute
  '/taxonomy': typeof TaxonomyRoute
  '/learn/identity': typeof LearnIdentityRoute
  '/learn/start': typeof LearnStartRoute
  '/learn/state': typeof LearnStateRoute
  '/learn/tiers': typeof LearnTiersRoute
  '/effects/': typeof EffectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/attention': typeof AttentionRoute
  '/bench': typeof BenchRoute
  '/demo': typeof DemoRoute
  '/findings': typeof FindingsRoute
  '/health': typeof HealthRoute
  '/taxonomy': typeof TaxonomyRoute
  '/learn/identity': typeof LearnIdentityRoute
  '/learn/start': typeof LearnStartRoute
  '/learn/state': typeof LearnStateRoute
  '/learn/tiers': typeof LearnTiersRoute
  '/effects': typeof EffectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/attention': typeof AttentionRoute
  '/bench': typeof BenchRoute
  '/demo': typeof DemoRoute
  '/findings': typeof FindingsRoute
  '/health': typeof HealthRoute
  '/taxonomy': typeof TaxonomyRoute
  '/learn/identity': typeof LearnIdentityRoute
  '/learn/start': typeof LearnStartRoute
  '/learn/state': typeof LearnStateRoute
  '/learn/tiers': typeof LearnTiersRoute
  '/effects/': typeof EffectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/attention'
    | '/bench'
    | '/demo'
    | '/findings'
    | '/health'
    | '/taxonomy'
    | '/learn/identity'
    | '/learn/start'
    | '/learn/state'
    | '/learn/tiers'
    | '/effects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/attention'
    | '/bench'
    | '/demo'
    | '/findings'
    | '/health'
    | '/taxonomy'
    | '/learn/identity'
    | '/learn/start'
    | '/learn/state'
    | '/learn/tiers'
    | '/effects'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/attention'
    | '/bench'
    | '/demo'
    | '/findings'
    | '/health'
    | '/taxonomy'
    | '/learn/identity'
    | '/learn/start'
    | '/learn/state'
    | '/learn/tiers'
    | '/effects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  AttentionRoute: typeof AttentionRoute
  BenchRoute: typeof BenchRoute
  DemoRoute: typeof DemoRoute
  FindingsRoute: typeof FindingsRoute
  HealthRoute: typeof HealthRoute
  TaxonomyRoute: typeof TaxonomyRoute
  LearnIdentityRoute: typeof LearnIdentityRoute
  LearnStartRoute: typeof LearnStartRoute
  LearnStateRoute: typeof LearnStateRoute
  LearnTiersRoute: typeof LearnTiersRoute
  EffectsIndexRoute: typeof EffectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taxonomy': {
      id: '/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof TaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effects/': {
      id: '/effects/'
      path: '/effects'
      fullPath: '/effects/'
      preLoaderRoute: typeof EffectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/tiers': {
      id: '/learn/tiers'
      path: '/learn/tiers'
      fullPath: '/learn/tiers'
      preLoaderRoute: typeof LearnTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/state': {
      id: '/learn/state'
      path: '/learn/state'
      fullPath: '/learn/state'
      preLoaderRoute: typeof LearnStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/start': {
      id: '/learn/start'
      path: '/learn/start'
      fullPath: '/learn/start'
      preLoaderRoute: typeof LearnStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/identity': {
      id: '/learn/identity'
      path: '/learn/identity'
      fullPath: '/learn/identity'
      preLoaderRoute: typeof LearnIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  AttentionRoute: AttentionRoute,
  BenchRoute: BenchRoute,
  DemoRoute: DemoRoute,
  FindingsRoute: FindingsRoute,
  HealthRoute: HealthRoute,
  TaxonomyRoute: TaxonomyRoute,
  LearnIdentityRoute: LearnIdentityRoute,
  LearnStartRoute: LearnStartRoute,
  LearnStateRoute: LearnStateRoute,
  LearnTiersRoute: LearnTiersRoute,
  EffectsIndexRoute: EffectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
